---
- name: change DNS server
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses: 
      - '192.168.158.10'
      - '192.168.158.11'
#
# Set IPv6 DNS Servers
#
#- name: Set IPv6 DNS servers on the adapter named Ethernet
#  ansible.windows.win_dns_client:
#    adapter_names: Ethernet
#    dns_servers:
#    - '2000:100:0:100::a'
#    - '2000:100:0:100::b'

- name: Change the hostname
  ansible.windows.win_hostname:
    name: "{{ sql1_server }}"
  register: res

- name: Reboot
  ansible.windows.win_reboot:
  when: res.reboot_required

- name: join domain
  win_domain_membership:
    dns_domain_name: "{{ domain }}"
    domain_ou_path: "ou=SQL,ou=Servers, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    domain_admin_user: "{{ domain_admin }}"
    domain_admin_password: "{{ domain_admin_password }}"
    state: domain
  register: domain_joined

- name: reboot after domain join
  win_reboot:
  when: domain_joined.reboot_required