variable "vsphere_user" {}
variable "vsphere_password" {}
variable "vsphere_server" {}
variable "vsphere_dc_name" {}
variable "vsphere_dscluster" {}
variable "vsphere_compute_cluster" {}
variable "vsphere_portgroup_name" {}
variable "vsphere_folder" {}
variable "vsphere_template_name" {}
variable "winadmin_password" {}
variable "PDC_name" {}
variable "SQLServer_name" {}
variable "SPServer_name" {}
variable "EXCServer_name" {}
variable "PDC_IPv6" {}
variable "SPServer_IPv6" {}
variable "SQLerver_IPv6" {}
variable "EXCServer_IPv6" {}
variable "subnet_prefix_IPv6" {}
variable "def_gw_IPv6" {}
variable "dns_server_IPv6" {}
variable "PDC_cpu_num" {}
variable "SQLServer_cpu_num" {}
variable "SPServer_cpu_num" {}
variable "EXCServer_cpu_num" {}
variable "PDC_mem" {}
variable "SQLServer_mem" {}
variable "SPServer_mem" {}
variable "EXCServer_mem" {}
variable "firmware" {}