variable "vsphere_user" {}
variable "vsphere_password" {}
variable "vsphere_server" {}
variable "vsphere_dc_name" {}
variable "vsphere_dscluster" {}
variable "vsphere_compute_cluster" {}
variable "vsphere_portgroup_name" {}
variable "vsphere_folder" {}
variable "vsphere_template_name" {}
variable "winadmin_password" {}
variable "PDC_name" {}
variable "SQLServer_name" {}
variable "SPServer_name" {}
variable "PDC_IPv4" {}
variable "SQLServer_IPv4" {}
variable "SPServer_IPv4" {}
variable "netmask_IPv4" {}
variable "def_gw_IPv4" {}
variable "dns_server_IPv4" {}
variable "PDC_cpu_num" {}
variable "SQLServer_cpu_num" {}
variable "SPServer_cpu_num" {}
variable "PDC_mem" {}
variable "SQLServer_mem" {}
variable "SPServer_mem" {}
variable "firmware" {}