variable "vsphere_user" {}
variable "vsphere_password" {}
variable "vsphere_server" {}
variable "vsphere_dc_name" {}
variable "vsphere_dscluster" {}
variable "vsphere_compute_cluster" {}
variable "vsphere_portgroup_name" {}
variable "vsphere_folder" {}
variable "vsphere_template_name" {}
variable "winadmin_password" {}
variable "PDC_name" {}
variable "PDC_IP_v4" {}
variable "netmask_v4" {}
variable "def_gw_v4" {}
variable "dns_server_v4" {}
variable "PDC_cpu_num" {}
variable "PDC_mem" {}
variable "firmware" {}