---
#
# Collect passwords from vault
#
- tasks:
    - name: include vault
      ansible.builtin.include_vars:
        file: passwords.yml
#
# Configure the primary domain controller
#
- hosts: Domain
  roles:
   - PDC
# 
# Domain join and install sql server
#
- hosts: SQL
  roles:
   - SQL
#   
# Domain join and install Sharepoint Server
#
- hosts: Sharepoint
  roles:
   - Sharepoint
#
# Domain join and install Exchange server
#
- hosts: Exchange
  roles:
   - Exchange