---
- hosts: All
  gather_facts: False
  var_files:
    - secret.yml
#
# Configure the primary domain controller
#
- hosts: Primary_Domain
  roles:
   - PDC
#
# Configure the secondary domain controller
#
#- hosts: Secondary_Domain
#  roles:
#  - SDC
# 
# Domain join and install sql server
#
- hosts: SQL
  roles:
   - SQL
#   
# Domain join and install Sharepoint Server
#
- hosts: Sharepoint
  roles:
   - Sharepoint
#
# Domain join and install Exchange server
#
- hosts: Exchange
  roles:
   - Exchange