---
#
# Configure the primary domain controller
#
- hosts: Primary_Domain
  gather_facts: False
  roles:
   - PDC
#
# Configure the secondary domain controller
#
- hosts: Secondary_Domain
  gather_facts: False
  roles:
  - SDC
# 
# Domain join and install sql server
#
- hosts: SQL1
  gather_facts: False
  roles:
   - SQL1
   # 
# Domain join and install sql server
#
- hosts: SQL2
  gather_facts: False
  roles:
   - SQL2
#   
# Domain join and install Sharepoint Server
#
- hosts: Sharepoint
  gather_facts: False
  roles:
   - Sharepoint
#
# Domain join and install Exchange server
#
- hosts: Exchange
  gather_facts: False
  roles:
   - Exchange