---
# Create Groups for Domain
- name: Create user group
  ansible.windows.win_group:
    name: Employees
    description: Employee Group
    state: present
# Create OU for User locations
- name: Install XactiveDirectory package for OU creation
  win_psmodule:
    name: ActiveDirectoryDSC
    state: present
- name: Create OU for Staff
  win_dsc:
    resource_name: ADOrganizationalUnit
    name: "Staff"
    path: "dc=test, dc=co, dc=uk"
    Description: "Staff OU"
    Ensure: present
- name: Create OU for Admin
  win_dsc:
    resource_name: ADOrganizationalUnit
    name: "Admins"
    path: "dc=test, dc=co, dc=uk"
    Description: "Administrator OU"
    Ensure: present
- name: Create OU for Service Accounts
  win_dsc:
    resource_name: ADOrganizationalUnit
    name: "Service Accounts"
    path: "dc=test, dc=co, dc=uk"
    Description: "Service Accounts OU"
    Ensure: present
# Create OU for Server locations
- name: Create OU for Servers
  win_dsc:
    resource_name: ADOrganizationalUnit
    name: "Servers"
    path: "dc=test, dc=co, dc=uk"
    Description: "Servers OU"
    Ensure: present  
- name: Create OU for Exchange Servers
  win_dsc:
    resource_name: ADOrganizationalUnit
    name: "Exchange"
    path: "ou=Servers,dc=test, dc=co, dc=uk"
    Description: "Exchange Servers OU"
    Ensure: present
- name: Create OU for Sharepoint Servers
  win_dsc:
    resource_name: ADOrganizationalUnit
    name: "Sharepoint"
    path: "ou=Servers,dc=test, dc=co, dc=uk"
    Description: "SharePoint OU"
    Ensure: present
- name: Create OU for SQL Servers
  win_dsc:
    resource_name: ADOrganizationalUnit
    name: "SQL"
    path: "ou=Servers,dc=test, dc=co, dc=uk"
    Description: "Microsoft SQL Servers OU"
    Ensure: present
# Create multiple users for Domain and add to respective groups
- name: Create administrator Account
  community.windows.win_domain_user:
    name: bakerg_admin
    firstname: Garry
    surname: Baker
    password: Pa55word
    state: present
    path: "ou=Admins, dc=test, dc=co, dc=uk"
    groups: 
    - Employees
    - Domain Users
    - Domain Admins
    - Enterprise Admins
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"
- name: Create Employee account
  community.windows.win_domain_user:
    name: bakerg
    firstname: Garry
    surname: Baker
    password: Pa55word
    state: present
    path: "ou=Staff, dc=test, dc=co, dc=uk"
    groups: 
    - Employees
    - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"
# Create Service Accounts
- name: Create SharePoint Farm Account
  community.windows.win_domain_user:
    name: sp_farm
    firstname: SharePoint Farm
    surname: Service Account
    password: Pa55word
    state: present
    path: "ou='Service Accounts', dc=test, dc=co, dc=uk"
    groups: 
    - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"
- name: Create SharePoint Admin Account
  community.windows.win_domain_user:
    name: sp_admin
    firstname: SharePoint Admin
    surname: Service Account
    password: Pa55word
    state: present
    path: "ou='Service Accounts', dc=test, dc=co, dc=uk"
    groups: 
    - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"
- name: Create SharePoint Pool Account
  community.windows.win_domain_user:
    name: sp_pool
    firstname: SharePoint Pool
    surname: Service Account
    password: Pa55word
    state: present
    path: "ou='Service Accounts', dc=test, dc=co, dc=uk"
    groups: 
    - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"
- name: Create SharePoint Services Account
  community.windows.win_domain_user:
    name: sp_services
    firstname: SharePoint Services
    surname: Service Account
    password: Pa55word
    state: present
    path: "ou='Service Accounts', dc=test, dc=co, dc=uk"
    groups: 
    - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"
- name: Create SharePoint Crawl Account
  community.windows.win_domain_user:
    name: sp_crawl
    firstname: SharePoint Crawl
    surname: Service Account
    password: Pa55word
    state: present
    path: "ou='Service Accounts', dc=test, dc=co, dc=uk"
    groups: 
    - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"
- name: Create SharePoint search Account
  community.windows.win_domain_user:
    name: sp_search
    firstname: SharePoint search
    surname: Service Account
    password: Pa55word
    state: present
    path: "ou='Service Accounts', dc=test, dc=co, dc=uk"
    groups: 
    - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"
- name: Create SharePoint My Site Pool Account
  community.windows.win_domain_user:
    name: sp_mysitepool
    firstname: SharePoint My Site Pool
    surname: Service Account
    password: Pa55word
    state: present
    path: "ou='Service Accounts', dc=test, dc=co, dc=uk"
    groups: 
    - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"
- name: Create SharePoint User Profile Sync Account
  community.windows.win_domain_user:
    name: sp_userprofilesync
    firstname: SharePoint User Profile Sync
    surname: Service Account
    password: Pa55word
    state: present
    path: "ou='Service Accounts', dc=test, dc=co, dc=uk"
    groups: 
    - Domain Users
    #- Needs additional permissions
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"
- name: Create SharePoint Workflow Manager Service Account
  community.windows.win_domain_user:
    name: wf_service
    firstname: SharePoint Workflow Manager
    surname: Service Account
    password: Pa55word
    state: present
    path: "ou='Service Accounts', dc=test, dc=co, dc=uk"
    groups: 
    - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"
- name: Create SharePoint Super User Account
  community.windows.win_domain_user:
    name: sp_portalsuperuser
    firstname: SharePoint Portal Super User
    surname: Service Account
    password: Pa55word
    state: present
    path: "ou='Service Accounts', dc=test, dc=co, dc=uk"
    groups: 
    - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"
- name: Create SharePoint Super Reader Account
  community.windows.win_domain_user:
    name: sp_portalsuperreader
    firstname: SharePoint Portal Super Reader
    surname: Service Account
    password: Pa55word
    state: present
    path: "ou='Service Accounts', dc=test, dc=co, dc=uk"
    groups: 
    - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"