---
# Create Groups for Domain
- name: Create user group
  ansible.windows.win_group:
    name: Employees
    description: Employee Group
    state: present
# Create OU for User locations (Staff, Admin)
- name: Install nuget packge for OU creation
  win_shell: install-packageprovider -name nuget -force
- name: Install XactiveDirectory package for OU creation
  win_psmodule:
    name: ActiveDirectoryDSC
    state: present
- name: Create OU for Staff
  win_dsc:
    resource_name: ADOrganizationalUnit
    name: "Staff"
    path: "dc={{ netbios_domain }}, dc={{ top_level_domain }}"
- name: Create OU for Admin
  win_dsc:
    resource_name: ADOrganizationalUnit
    name: "Admins"
    path: "dc={{ netbios_domain }}, dc={{ top_level_domain }}"
# Create multiple users for Domain and add to respective groups
- name: Create administrator Account
  community.windows.win_domain_user:
    name: bakerg_admin
    firstname: Garry
    surname: Baker
    password: Pa55word
    state: present
    path: "ou=Admins, dc={{ netbios_domain }}, dc={{ top_level_domain }}"
    groups: 
    - Employees
    - Domain Users
    - Domain Admins
    - Enterprise Admins
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"
- name: Create Employee account John
  community.windows.win_domain_user:
    name: bakerg
    firstname: Garry
    surname: Baker
    password: Pa55word
    state: present
    path: "ou=Staff, dc={{ netbios_domain }}, dc={{ top_level_domain }}"
    groups: 
    - Employees
    - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"
