---
ansible_user: administrator
ansible_password: "Pa55word"
ansible_port: 5985
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore

domain: "test.co.uk"
netbios_domain: "test"
middle_level_domain: "co"
end_level_domain: "uk"
domain_admin: "{{ ansible_user }}@{{ domain }}"
domain_admin_username: "{{ ansible_user }}"
domain_admin_password: "Pa55word"
domain_safemode_password: "Pa55word"

primary_domain_controller: "testdc001"
sp_server: "testsp001"

fqdn_primary_domain_controller: "{{ primary_domain_controller }}.{{ domain }}"
fqdn_sql_server: "{{ sql_server }}.{{ domain }}"