---
- name: Initialize disk 1
  community.windows.win_initialize_disk:
    disk_number: 1

- name: Create a partition with drive letter D
  community.windows.win_partition:
    drive_letter: D
    partition_size: -1
    disk_number: 1

- name: Full format the newly created partition as NTFS and label it
  community.windows.win_format:
    drive_letter: D
    file_system: NTFS
    new_label: Active Directory
    full: True

- name: Initialize disk 2
  community.windows.win_initialize_disk:
    disk_number: 2

- name: Create a partition with drive letter E
  community.windows.win_partition:
    drive_letter: E
    partition_size: -1
    disk_number: 2

- name: Full format the newly created partition as NTFS and label it
  community.windows.win_format:
    drive_letter: E
    file_system: NTFS
    new_label: System State
    full: True

- name: Change the hostname
  ansible.windows.win_hostname:
    name: "{{ primary_domain_controller }}"
  register: res

- name: Reboot
  ansible.windows.win_reboot:
  when: res.reboot_required

#- name: install active directory
#  win_domain:
#    dns_domain_name: "{{ domain }}"
#    domain_netbios_name: "{{ netbios_domain }}"
#    safe_mode_password: "{{ domain_safemode_password }}"

- name: Create new Windows domain in a new forest with specific parameters
  win_domain:
    create_dns_delegation: no
    database_path: D:\NTDS
    dns_domain_name: "{{ domain }}"
    #domain_mode: Win2012R2
    domain_netbios_name: "{{ netbios_domain }}"
    #forest_mode: Win2012R2
    safe_mode_password: "{{ domain_safemode_password }}"
    sysvol_path: E:\SYSVOL
  register: domain_install

  #register: ad

- name: reboot server
  win_reboot:
    msg: "Installing AD. Rebooting..."
    pre_reboot_delay: 15
    reboot_timeout: 600
    post_reboot_delay: 420
  when: ad.changed