---
# Configure the primary domain controller
- hosts: pdc
  roles:
   - pdc
   - pdc_userdata
   #- pdc_gpos

# Domain join and install Exchange server
- hosts: exc
  roles:
   - exc

# Domain join and install sql server
- hosts: sp001
  roles:
   - sp001
- hosts: sp002
  roles:
   - sp002
# Domain join and install Sharepoint Server
- hosts: sql
  roles:
   - sql