---
- hosts: pdc
  roles:
    - pdc
    - pdc_userdata
    - common

- hosts: exc
  roles:
    - exc
    - common

- hosts: sql
  roles:
    - sql
    - common

- hosts: sp
  roles:
    - sp
    - common