variable "vsphere_user" {}
variable "vsphere_password" {}
variable "vsphere_server" {}
variable "vsphere_dc_name" {}
variable "vsphere_dscluster" {}
variable "vsphere_compute_cluster" {}
variable "vsphere_portgroup_name" {}
variable "vsphere_folder" {}
variable "vsphere_template_name" {}
variable "winadmin_password" {}
variable "PDC_name" {}
variable "ReplicaDC_name" {}
variable "FileServer_name" {}
variable "PrtServer_name" {}
variable "SQLServer_name" {}
variable "SPServer_name" {}
variable "ExcServer_name" {}
variable "PDC_IP" {}
variable "ReplicaDC_IP" {}
variable "FileServer_IP" {}
variable "PrtServer_IP" {}
variable "SQLServer_IP" {}
variable "SPServer_IP" {}
variable "ExcServer_IP" {}
variable "netmask" {}
variable "def_gw" {}
variable "dns_server" {}
variable "PDC_cpu_num" {}
variable "ReplicaDC_cpu_num" {}
variable "FileServer_cpu_num" {}
variable "PrtServer_cpu_num" {}
variable "SQLServer_cpu_num" {}
variable "SPServer_cpu_num" {}
variable "ExcServer_cpu_num" {}
variable "PDC_mem" {}
variable "ReplicaDC_mem" {}
variable "FileServer_mem" {} 
variable "PrtServer_mem" {}
variable "SQLServer_mem" {}
variable "SPServer_mem" {}
variable "ExcServer_mem" {}
variable "firmware" {}