-  name: "Create a GPO"
   hosts: windows
   tasks:
   - name: "Install GroupPolicyDSC"
     win_psmodule:
        name: GroupPolicyDSC
        state: present

   - name: "Create GPO"
     win_dsc:
        resource_name: GroupPolicy
        name: "SQL Servers"
        status: allsettingsenabled
        ensure: present

    - name: "Create GPO"
      win_dsc:
        resource_name: GroupPolicy
        name: "Firewall"
        status: allsettingsenabled
        ensure: present