---
# Domain Group Creation
#
# Should these be Domain Local or Domain Global Groups?
#
# Create Employees Group
- name: Create Employees Group
  ansible.windows.win_group:
    name: Employees
    description: Employee Group
    state: present

# Create SQL Server Local Administrator
- name: Create SQL Local Administrator Group
  ansible.windows.win_group:
    name: SQL_LocalAdmin
    description: SQL Server Local Administrator
    state: present

# Create SQL Server SysAdmin
- name: Create SQL SysAdmin Group
  ansible.windows.win_group:
    name: SysAdmin
    description: SQL Server SysAdmin
    state: present

# Create SQL DB_Creator
- name: Create SQL DB_Creator Group
  ansible.windows.win_group:
    name: DB_Creator
    description: SQL Server DB_Creator
    state: present
    
# Create SQL SecurityAdmin 
- name: Create SQL SecurityAdmin Group
  ansible.windows.win_group:
    name: SecurityAdmin
    description: SQL Server SecurityAdmin
    state: present

# Domain OU Creation
# Create OU for User locations
- name: Install XactiveDirectory package for OU creation
  win_psmodule:
    name: ActiveDirectoryDSC
    state: present

- name: Create OU for Staff
  win_dsc:
    resource_name: ADOrganizationalUnit
    name: "Staff"
    path: "dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    Description: "Staff OU"
    Ensure: present

- name: Create OU for Admin
  win_dsc:
    resource_name: ADOrganizationalUnit
    name: "Admins"
    path: "dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    Description: "Administrator OU"
    Ensure: present

- name: Create OU for Service Accounts
  win_dsc:
    resource_name: ADOrganizationalUnit
    name: "Service Accounts"
    path: "dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    Description: "Service Accounts OU"
    Ensure: present

# Create OU for Server locations
- name: Create OU for Servers
  win_dsc:
    resource_name: ADOrganizationalUnit
    name: "Servers"
    path: "dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    Description: "Servers OU"
    Ensure: present  

- name: Create OU for Exchange Servers
  win_dsc:
    resource_name: ADOrganizationalUnit
    name: "Exchange"
    path: "ou={{ Member_Servers }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    Description: "Exchange Servers OU"
    Ensure: present

- name: Create OU for Sharepoint Servers
  win_dsc:
    resource_name: ADOrganizationalUnit
    name: "Sharepoint"
    path: "ou={{ Member_Servers }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    Description: "SharePoint OU"
    Ensure: present

- name: Create OU for SQL Servers
  win_dsc:
    resource_name: ADOrganizationalUnit
    name: "SQL"
    path: "ou={{ Member_Servers }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    Description: "Microsoft SQL Servers OU"
    Ensure: present