---
# Domain Group Creation
#
# Should these be Domain Local or Domain Global Groups?
#
# Create Employees Group
#
- name: Create Employees Group
  ansible.windows.win_group:
    name: Employees
    description: Employee Group
    state: present
#
# Create SQL Server Local Administrator
#
- name: Create SQL Local Administrator Group
  ansible.windows.win_group:
    name: SQL_LocalAdmin
    description: SQL Server Local Administrator
    state: present
#
# Create SQL Server SysAdmin
#
- name: Create SQL SysAdmin Group
  ansible.windows.win_group:
    name: SysAdmin
    description: SQL Server SysAdmin
    state: present
#
# Create SQL DB_Creator
#
- name: Create SQL DB_Creator Group
  ansible.windows.win_group:
    name: DB_Creator
    description: SQL Server DB_Creator
    state: present
#
# Create SQL SecurityAdmin
#
- name: Create SQL SecurityAdmin Group
  ansible.windows.win_group:
    name: SecurityAdmin
    description: SQL Server SecurityAdmin
    state: present