---
#
# Initiate data disks
#
- include_tasks: initiate_disks.yml
#
# Build Microsoft Active Directory
#
- include_tasks: build_domain.yml
#
# Configure Group Policys
#
# - include: gpos.yml
#
# Configure DNS
#
# - include: dns.yml
#
# Configure DHCP
#
# - include: dhcp.yml
#
# Configure Active Directory Groups, OUs, Service Account and Users
#
# Create Active Directory Organisation Units
#
- include_tasks: ous.yml
#
# Create Active Directory Groups
#
- include_tasks: groups.yml
#
# Create Active Directory Service Accounts
#
- include_tasks: service.yml
#
# Create Active Directory Users
#
- include_tasks: users.yml