---
#
# Initiate data disks
#
- include: initiate_disks.yml
#
# Build Microsoft Active Directory
#
- include: build_domain.yml
#
# Configure Group Policys
#
# - include: gpos.yml
#
# Configure DNS
#
# - include: dns.yml
#
# Configure DHCP
#
# - include: dhcp.yml
#
# Configure Active Directory OUs
#
- include: ous.yml
#
# Configure Active Directory Groups
#
- include: groups.yml
#
# Configure Active Directory Service Accounts
#
- include: service_accounts.yml
#
# Configure Active Directory User Acconts
#
- include: users.yml