---
#
# Initiate data disks
#
- include_tasks: initiate_disks.yml
#
# Build Microsoft Active Directory
#
- include_tasks: build_domain.yml
#
# Configure Group Policys
#
# - include: gpos.yml
#
# Configure DNS
#
# - include: dns.yml
#
# Configure DHCP
#
# - include: dhcp.yml
#
# Configure Active Directory Groups, OUs, Service Account and Users
#
- include_tasks: active_directory.yml