---
#
# Domain Service Account Creation
#
# Setup SQL Server Service Account
#
- name: Create SQL Service Account
  community.windows.win_domain_user:
    name: "{{ mssql_sqlsvc_account }}"
    firstname: "{{ mssql_instance_name }}"
    surname: SQLSvc
    password: "{{ mssql_sqlsvc_password }}"
    description: "SQL Service account for {{ sql_server }}\\{{ mssql_instance_name }}"
    password_never_expires: true
    user_cannot_change_password: true
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups:
      - Domain Users
      - SQL_LocalAdmin
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"
  tags: service_account
#  delegate_to: "{{ primary_domain_controller }}"
#
# Setup SQL Server Agent Service Account
#
- name: Create SQL Server Agent Service Account
  community.windows.win_domain_user:
    name: "{{ mssql_agentsvc_account }}"
    firstname: "{{ mssql_instance_name }}"
    surname: AgentSvc
    password: "{{ mssql_agentsvc_password }}"
    description: "SQL Agent service account for {{ sql_server }}\\{{ mssql_instance_name }}"
    password_never_expires: true
    user_cannot_change_password: true
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups:
      - Domain Users
      - SQL_LocalAdmin
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"
  tags: service_account
  #delegate_to: "{{ primary_domain_controller }}"
#
# Create SQL Server Farm Service Accounts
#
- name: Create SharePoint Farm Account
  community.windows.win_domain_user:
    name: sp_farm
    firstname: SharePoint Farm
    surname: Service Account
    password: Pa55word
    description: SharePoint Farm Service Account
    password_never_expires: true
    user_cannot_change_password: true
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Domain Users
    - DB_Creator
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"

- name: Create SharePoint Admin Account
  community.windows.win_domain_user:
    name: sp_admin
    firstname: SharePoint Admin
    surname: Service Account
    password: Pa55word
    description: SharePoint Admin Service Account
    password_never_expires: true
    user_cannot_change_password: true
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Domain Users
    - SysAdmin
    - SecurityAdmin
    - DB_Creator
    - SQL_LocalAdmin
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"

- name: Create SharePoint Pool Account
  community.windows.win_domain_user:
    name: sp_pool
    firstname: SharePoint Pool
    surname: Service Account
    password: Pa55word
    description: SharePoint Pool Service Account
    password_never_expires: true
    user_cannot_change_password: true
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"

- name: Create SharePoint Services Account
  community.windows.win_domain_user:
    name: sp_services
    firstname: SharePoint Services
    surname: Service Account
    password: Pa55word
    description: SharePoint Services Account
    password_never_expires: true
    user_cannot_change_password: true
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"

- name: Create SharePoint Crawl Account
  community.windows.win_domain_user:
    name: sp_crawl
    firstname: SharePoint Crawl
    surname: Service Account
    password: Pa55word
    description: SharePoint Crawl Service Account
    password_never_expires: true
    user_cannot_change_password: true
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"

- name: Create SharePoint Search Account
  community.windows.win_domain_user:
    name: sp_search
    firstname: SharePoint search
    surname: Service Account
    password: Pa55word
    description: SharePoint search Service Account
    password_never_expires: true
    user_cannot_change_password: true
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Domain Users
    - SysAdmin
    - SQL_LocalAdmin
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"

- name: Create SharePoint My Site Pool Account
  community.windows.win_domain_user:
    name: sp_mysitepool
    firstname: SharePoint My Site Pool
    surname: Service Account
    password: Pa55word
    description: SharePoint MySitePool Service Account
    password_never_expires: true
    user_cannot_change_password: true
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"

- name: Create SharePoint User Profile Sync Account
  community.windows.win_domain_user:
    name: sp_userprofilesync
    firstname: SharePoint User Profile Sync
    surname: Service Account
    password: Pa55word
    description: SharePoint User Profile Sync Service Account
    password_never_expires: true
    user_cannot_change_password: true
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Domain Users
    #- Needs additional permissions
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"

- name: Create SharePoint Workflow Manager Service Account
  community.windows.win_domain_user:
    name: wf_service
    firstname: SharePoint Workflow Manager
    surname: Service Account
    password: Pa55word
    description: SharePoint Workflow Manager Service Account
    password_never_expires: true
    user_cannot_change_password: true
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Domain Users
    - SysAdmin
    - SQL_LocalAdmin
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"

- name: Create SharePoint Super User Account
  community.windows.win_domain_user:
    name: sp_portalsuperuser
    firstname: SharePoint Portal Super User
    surname: Service Account
    password: Pa55word
    description: SharePoint Portal Super User
    password_never_expires: true
    user_cannot_change_password: true
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"

- name: Create SharePoint Super Reader Account
  community.windows.win_domain_user:
    name: sp_portalsuperreader
    firstname: SharePoint Portal Super Reader
    surname: Service Account
    password: Pa55word
    description: SharePoint Super Reader
    password_never_expires: true
    user_cannot_change_password: true
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"