---
#
# Domain Service Account Creation
#
# Setup service accounts for SQL Server
#
- name: Active Directory | Ensure SQL Service account is present
  community.windows.win_domain_user:
    name: "{{ mssql_sqlsvc_account }}"
    firstname: "{{ mssql_instance_name }}"
    surname: SQLSvc
    password: "{{ mssql_sqlsvc_account_pass }}"
    password_never_expires: yes
    user_cannot_change_password: yes
    description: "SQL Service account for {{ sql_server }}\\{{ mssql_instance_name }}"
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups:
      - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"
  tags: service_account
#  delegate_to: "{{ primary_domain_controller }}"

- name: Active Directory | Ensure SQL Agent Service account is present
  community.windows.win_domain_user:
    name: "{{ mssql_agentsvc_account }}"
    firstname: "{{ mssql_instance_name }}"
    surname: AgentSvc
    password: "{{ mssql_agentsvc_account_pass }}"
    password_never_expires: yes
    user_cannot_change_password: yes
    description: "SQL Agent service account for {{ sql_server }}\\{{ mssql_instance_name }}"
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups:
      - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"
  delegate_to: "{{ primary_domain_controller }}"
  tags: service_account
#
# Create SQL Server Farm Service Accounts
#
- name: Create SharePoint Farm Account
  community.windows.win_domain_user:
    name: sp_farm
    firstname: SharePoint Farm
    surname: Service Account
    password: Pa55word
    Description: SharePoint Farm Service Account
    PasswordNeverExpires: True
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Domain Users
    - DB_Creator
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"

- name: Create SharePoint Admin Account
  community.windows.win_domain_user:
    name: sp_admin
    firstname: SharePoint Admin
    surname: Service Account
    password: Pa55word
    Description: SharePoint Admin Service Account
    PasswordNeverExpires: True
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Domain Users
    - SysAdmin
    - SecurityAdmin
    - DB_Creator
    - SQL_LocalAdmin
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"

- name: Create SharePoint Pool Account
  community.windows.win_domain_user:
    name: sp_pool
    firstname: SharePoint Pool
    surname: Service Account
    password: Pa55word
    Description: SharePoint Pool Service Account
    PasswordNeverExpires: True
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"

- name: Create SharePoint Services Account
  community.windows.win_domain_user:
    name: sp_services
    firstname: SharePoint Services
    surname: Service Account
    password: Pa55word
    Description: SharePoint Services Account
    PasswordNeverExpires: True
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"

- name: Create SharePoint Crawl Account
  community.windows.win_domain_user:
    name: sp_crawl
    firstname: SharePoint Crawl
    surname: Service Account
    password: Pa55word
    Description: SharePoint Crawl Service Account
    PasswordNeverExpires: True
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"

- name: Create SharePoint Search Account
  community.windows.win_domain_user:
    name: sp_search
    firstname: SharePoint search
    surname: Service Account
    password: Pa55word
    Description: SharePoint search Service Account
    PasswordNeverExpires: True
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Domain Users
    - SysAdmin
    - SQL_LocalAdmin
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"

- name: Create SharePoint My Site Pool Account
  community.windows.win_domain_user:
    name: sp_mysitepool
    firstname: SharePoint My Site Pool
    surname: Service Account
    password: Pa55word
    Description: SharePoint MySitePool Service Account
    PasswordNeverExpires: True
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"

- name: Create SharePoint User Profile Sync Account
  community.windows.win_domain_user:
    name: sp_userprofilesync
    firstname: SharePoint User Profile Sync
    surname: Service Account
    password: Pa55word
    Description: SharePoint User Profile Sync Service Account
    PasswordNeverExpires: True
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Domain Users
    #- Needs additional permissions
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"

- name: Create SharePoint Workflow Manager Service Account
  community.windows.win_domain_user:
    name: wf_service
    firstname: SharePoint Workflow Manager
    surname: Service Account
    password: Pa55word
    Description: SharePoint Workflow Manager Service Account
    PasswordNeverExpires: True
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Domain Users
    - SysAdmin
    - SQL_LocalAdmin
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"

- name: Create SharePoint Super User Account
  community.windows.win_domain_user:
    name: sp_portalsuperuser
    firstname: SharePoint Portal Super User
    surname: Service Account
    password: Pa55word
    Description: SharePoint Portal Super User
    PasswordNeverExpires: True
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"

- name: Create SharePoint Super Reader Account
  community.windows.win_domain_user:
    name: sp_portalsuperreader
    firstname: SharePoint Portal Super Reader
    surname: Service Account
    password: Pa55word
    Description: SharePoint Super Reader
    password_never_expires: yes
    user_cannot_change_password: yes
    state: present
    path: "ou={{ Service_Accounts }}, dc={{ netbios_domain }}, dc={{ middle_level_domain }}, dc={{ end_level_domain }}"
    groups: 
    - Domain Users
    domain_username: "{{ domain_admin_username }}"
    domain_password: "{{ domain_admin_password }}"
    domain_server: "{{ primary_domain_controller }}"